language: objective-c
osx_image: xcode9
script:
  - xcodebuild build-for-testing test-without-building -project XMLDecoder.xcodeproj -scheme XMLDecoder -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
